site_name: Salesforce Inspector reloaded
site_url: https://tprouvot.github.io/Salesforce-Inspector-reloaded/
repo_url: https://github.com/tprouvot/Salesforce-Inspector-reloaded
site_author: Thomas Prouvot

nav:
  - Home: index.md
  - Getting Started:
      - Welcome: welcome.md
      - Configure Connected App: how-to/#use-sf-inspector-with-a-connected-app
      - Release Notes: release-note.md
  - Features:
      - Data Management:
          - Data Export: data-export.md
          - Data Import: data-import.md
      - Metadata:
          - Download Metadata: download-metadata.md
          - Field Creator: field-creator.md
      - API:
          - Event Monitor: event-monitor.md
          - REST Explorer: rest-explorer.md
          - Org Limits: limits.md
      - How-To: how-to.md
  - Support:
      - Troubleshooting: troubleshooting.md
      - Privacy Policy: privacy.md
      - Donate: donate.md
      - Developer Notes: dev-notes.md

theme:
  name: material
  logo: assets/images/icon128.png
  favicon: assets/images/icon128.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.expand
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tprouvot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thomasprouvot/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - CHANGES.md
        - README.md
        - PRIVACY.md
      check_paths: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji

copyright: |
  &copy; 2025 <a href="https://github.com/tprouvot" target="_blank" rel="noopener">Thomas Prouvot</a>
